version: "3"

services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=commander
      - POSTGRES_PASSWORD=commander
      - POSTGRES_DB=commanderdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
